config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'realisations', to: 'pages#realisations', as: :realisations
  get 'cms', to: 'pages#cms', as: :cms
  get "contacts/new", to: "contacts#new"
  post "contacts", to: "contacts#create"
  get 'home', to: 'pages#home', as: :home
  # get 'pages/realisations'
  # get 'pages/cms'
  # get 'pages/contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    @contact.save
      if @contact.save
        redirect_to root_path
      end
  end

  private

  def contact_params
    params.require(:contact).permit(:project_name, :project_type, :project_theme,
    :project_format, :project_description, :project_budget, :project_date_end,
    :first_name, :last_name, :society, :address, :zip, :town, :email, :phone,
    :how_providz)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def realisations
  end

  def cms
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contacts/new.html.erb
<div class="background-contact">
  <div class="background2">
    <div class="container">
      <div class="row col-xs-12">
        <div class="navbar-wagon navbar-contact">
          <!-- Logo -->
          <a href="/" class="navbar-wagon-brand">
            <%= image_tag "logo.png"%>
          </a>
          <!-- Right Navigation -->
          <div class="navbar-wagon-right "> <!-- hidden-xs hidden-sm -->
            <a href="" class="navbar-wagon-item navbar-wagon-link" style="color: black;">Concept</a>
            <%= link_to "Réalisations", realisations_path, class: "navbar-wagon-item navbar-wagon-link", :style=>'color: black;'%>
            <!-- <a href="" class="navbar-wagon-item navbar-wagon-link">Réalisations</a> -->
            <a href="" class="navbar-wagon-item navbar-wagon-link btn-start-brief">START BRIEF</a>
          </div>
        </div>
      <div class="col-md-6 col-md-offset-3 header-contact">
        <div class="titre-contact">
          <h2>Démarrer votre brief</h2>
        </div>
        <div class="teaser-contact">
          <h4>Vous avez un projet audiovisuel ?</h4>
          <h4>Vous ne voulez plus perdre de temps à chercher</h4>
          <h4>le bon prestataire pour la bonne vidéo ?</h4>
        </div>
        <div>
          <p>Providz étudie tous vos projets vidéos et vous accompagne pour définir vos besoins en fonction de votre budget.</p>
        </div>
        <br>
        <br>
        <br>
      </div>
      <%= simple_form_for(@contact) do |f| %>
      <div class="col-md-6 col-md-offset-3">
        <h3>A propos de votre projet</h3>
        <p>N'oubliez pas que plus les informations sont complètes, plus cela sera simple de vous trouver une équipe !</p>
        <div class="form-row">
          <div class="form-group col-md-6">
            <%= f.label :"Nom du projet" %>
            <%= f.text_field :project_name, class:"form-control" %>
          </div>
          <div class="form-group col-md-6">
            <%= f.label :"Type de projet" %>
            <%= f.text_field :project_type, class:"form-control" %>
          </div>
        </div>
        <div class="form-row">
          <div class="form-group col-md-6">
            <%= f.label :"Theme abordés" %>
            <%= f.text_field :project_theme, class:"form-control" %>
          </div>
          <div class="form-group col-md-6">
            <%= f.label :"Format souhaité" %>
            <%= f.text_field :project_format, class:"form-control" %>
          </div>
        </div>
        <div class="form-group col-md-12">
          <%= f.label :"Description de votre projet" %>
          <%= f.text_field :project_description, class:"form-control" %>
        </div>
        <div class="form-row">
          <div class="form-group col-md-6">
            <%= f.label :"Votre budget" %>
            <%= f.text_field :project_budget, class:"form-control" %>
          </div>
          <div class="form-group col-md-6">
            <%= f.label :"Délais espéré" %>
            <%= f.text_field :project_date_end, class:"form-control", placeholder:"jj/mm/aaaa" %>
          </div>
          <br>
          <h3>A propos de vous</h3>
          <p>Apprenons à mieux nous connaitre</p>
        </div>
        <div class="form-row">
          <div class="form-group col-md-6">
            <%= f.label :"Prénom" %>
            <%= f.text_field :first_name, class:"form-control" %>
          </div>
          <div class="form-group col-md-6">
            <%= f.label :"Nom" %>
            <%= f.text_field :last_name, class:"form-control" %>
          </div>
        </div>
        <div class="form-group col-md-12">
          <%= f.label :"Société" %>
          <%= f.text_field :society, class:"form-control" %>
        </div>
        <div class="form-group col-md-12">
          <%= f.label :"Adresse" %>
          <%= f.text_field :address, class:"form-control" %>
        </div>
        <div class="form-row">
          <div class="form-group col-md-6">
            <%= f.label :"Code postal" %>
            <%= f.text_field :zip, class:"form-control" %>
          </div>
          <div class="form-group col-md-6">
            <%= f.label :"Ville" %>
            <%= f.text_field :town, class:"form-control" %>
          </div>
        </div>
        <div class="form-row">
          <div class="form-group col-md-6">
            <%= f.label :"Email" %>
            <%= f.text_field :email, class:"form-control" %>
          </div>
          <div class="form-group col-md-6">
            <%= f.label :"Téléphone" %>
            <%= f.text_field :phone, class:"form-control" %>
          </div>
        </div>
        <div class="form-group col-md-12">
          <%= f.label :"Comment avez vous connu notre site ?" %>
          <%= f.text_field :how_providz, class:"form-control" %>
        </div>
        <%= f.submit "Envoyer le projet", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Providz</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= yield %>
    <%= javascript_include_tag "application" %>
    <%= javascript_pack_tag "application" %>
  </body>
</html>

app/views/pages/cms.html.erb
<h1>Pages#cms</h1>
<p>Find me in app/views/pages/cms.html.erb</p>

app/views/pages/home.html.erb
<html>
  <head>
    <body>
      <div class="container home-image">
        <div class="row col-xs-12">
          <%= render "shared/navbar" %>
        </div>
        <div class="row logo-p col-xs-12">
              <%= image_tag "P.png"%>
        </div>
        <div class="row punchline col-xs-12">
          <p>Bookez les intermittents et freelances</p>
          <p>qui donneront vie à votre projet.</p>
        </div>
        <div class="row crew col-xs-12">
          <a href="" class="navbar-wagon-item navbar-wagon-link btn-crew">ENGAGEZ LE CREW DE VOS RÊVES</a>
        </div>
        <div class = "row anim col-xs-12"></div>
        <div class=" row providz-premium col-xs-12">
          <div>
            <h3>Providz votre accompagnateur premium</h3>
            <h3>dans vos réalisations audiovisuelles.</h3>
          </div>
        </div>
        <div class="row panel-real col-xs-12">
          <h3>De quoi sommes-nous capables ?</h3>
          <p>Découvrez notre panel de réalisations possibles.</p>
        </div>
        <div class="row col-xs-12">
          <%= render "shared/footer" %>
        </div>
      </div>
    </body>
  </head>
</html>

app/views/pages/realisations.html.erb
<h1>Pages#realisations</h1>
<p>Find me in app/views/pages/realisations.html.erb</p>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="center-bloc">
    <p>test</p>
  </div>
  <div class="footer-bloc">
    <h3>Providz</h3>
    <ul>
      <li>Concept</li>
      <li>Mention légales</li>
      <li>CGU</li>
      <li>La Team</li>
    </ul>
  </div>
  <div class="footer-bloc">
    <h3>Social</h3>
    <ul>
      <li><i class="fab fa-facebook-f"></i> Facebook</li>
      <li><i class="fab fa-linkedin-in"></i> LinkedIn</li>
      <li><i class="fab fa-vimeo-v"></i> Vimeo</li>
    </ul>
  </div>
  <div class="footer-bloc">
    <h3>Contact</h3>
    <ul>
      <li>Téléphone : </li>
      <li>Email :</li>
    </ul>
  </div>
  <div class="footer-bloc">
    <h3>Tu es technicien ?</h3>
    <p>Phrase pour interpeler et faire le lien avec Opside</p>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
    <%= image_tag "logo.png"%>
  </a>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right "> <!-- hidden-xs hidden-sm -->
    <a href="" class="navbar-wagon-item navbar-wagon-link">Concept</a>
    <%= link_to "Réalisations", realisations_path, class: "navbar-wagon-item navbar-wagon-link"%>
    <!-- <a href="" class="navbar-wagon-item navbar-wagon-link">Réalisations</a> -->
    <a href="" class="navbar-wagon-item navbar-wagon-link btn-start-brief">START BRIEF</a>
  </div>
  <!-- Dropdown appearing on mobile only -->
 <!-- <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fas fa-bars dropdown-toggle" data-toggle="dropdown" role="button"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Concept</a></li>
        <li><a href="#">Réalisations</a></li>
        <li><a href="#">START BRIEF</a></li>
      </ul>
    </div>
  </div>
</div>
-->